// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://updvizolxmlzwyfpzmqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZHZpem9seG1send5ZnB6bXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzU3MTUsImV4cCI6MjA2NTU1MTcxNX0.Pxet5OHZPRHYn5CaA6dV_oUhNHCYES2WJLLZXyyjsP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);